services:
  fillarpd:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: fillarpd:latest # This is setting the local build name
    container_name: fillarpd
    restart: always
    # required for the container to function peroprly
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
